version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0

workflows:
  build:
    jobs:
      - cypress/run: # "run" job comes from "cypress" orb
          record: true
          parallel: true
          parallelism: 5
          store_artifacts: true
          working_directory: cypress/results
          post-steps:
            - store_test_results:
                path: cypress/results
