version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0

workflows:
  build:
    jobs:
      - cypress/run: # "run" job comes from "cypress" orb
          record: true
          parallel: true
          parallelism: 5
